### ISSUE TITLE
Newly generated file not included in commit

### ISSUE THREAD

**Issue by enyo** [crazy-max/ghaction-github-pages#120]
I have a directory `website/` with my full jekyll site, but I generate the `index.md` file before I want to publish:

```
      - uses: actions/setup-node@v2.1.1
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build-website
      - run: ls -la website/
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          build_dir: website
```

It properly deploys the site to `gh-pages` but it is missing the generated `index.md` file from the `npm run build-website` step.
I added a `ls -la website/` right after and the file is there:

![image](https://user-images.githubusercontent.com/133277/88484732-15aaf180-cf71-11ea-9642-3b89c10a1fd7.png)

Do you have an idea what might be going on here?
