### ISSUE TITLE
File already exists error

### ISSUE THREAD

**Issue by ewpratten** [crazy-max/ghaction-github-pages#121]
### Behaviour

When deploying a directory with this action, I am getting the error:
```
##[error]EEXIST: file already exists, symlink '/home/runner/.cache/bazel/_bazel_runner/17d8e9b30b69e9aeac686c3673f39b5a/execroot/highschool_notes/bazel-out/k8-fastbuild/bin' -> '/tmp/github-pages-vbZ3SF'
```

For clarification, I am using the [bazel](https://bazel.build) buildsystem and pandoc to generate some HTML outputs from LaTeX files. After running, Bazel creates the following symlinks in the workspace directory:

```
bazel-bin -> /home/runner/.cache/bazel/_bazel_runner/17d8e9b30b69e9aeac686c3673f39b5a/execroot/highschool_notes/bazel-bin
bazel-highschool_notes -> /home/runner/.cache/bazel/_bazel_runner/17d8e9b30b69e9aeac686c3673f39b5a/execroot/highschool_notes/bazel-highschool_notes
bazel-out -> /home/runner/.cache/bazel/_bazel_runner/17d8e9b30b69e9aeac686c3673f39b5a/execroot/highschool_notes/bazel-out
bazel-testlogs -> /home/runner/.cache/bazel/_bazel_runner/17d8e9b30b69e9aeac686c3673f39b5a/execroot/highschool_notes/bazel-testlogs
```

I would expect that this just deploys as per usual (I have no problems in many other projects)

### Configuration

* Repository URL (if public): 
* Build URL (if public): 

```yml
name: Deploy docs

on:
  push:
    branches:
      - master
 
jobs:
  
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"

      - name: Install pandoc
        run: |
          sudo apt install pandoc texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra -y

      - name: Build
        run: |
          "${GITHUB_WORKSPACE}/bin/bazel" clean
          "${GITHUB_WORKSPACE}/bin/bazel" build //:all

      - name: Check GitHub Pages status
        uses: crazy-max/ghaction-github-status@v1
        with:
          pages_threshold: major_outage

      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: bazel-bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

### Logs

[logs_7.zip](https://github.com/crazy-max/ghaction-github-pages/files/5028740/logs_7.zip)
