### ISSUE TITLE
EEXIST: file already exists

### ISSUE THREAD

**Issue by smoak** [crazy-max/ghaction-github-pages#129]
### Behaviour

When I am deploying a directory I am getting this error:

`EEXIST: file already exists, mkdir '/tmp/github-pages-3fqEIE/lib/absinthe/priv'`

I am using mix (elixir's build tool) to [build a release](https://hexdocs.pm/mix/Mix.Tasks.Release.html). After running, mix will create a `_build/prod` directory with all the files needed to run the app.

#### Expected behaviour

Deploys as usual

#### Actual behaviour

Error: `EEXIST: file already exists, mkdir '/tmp/github-pages-3fqEIE/lib/absinthe/priv'`

### Configuration

* Repository URL (if public): https://github.com/smoak/teamcowboy-graphql
* Build URL (if public): https://github.com/smoak/teamcowboy-graphql/runs/1386551167

```yml
name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Elixir
        uses: actions/setup-elixir@v1.0.0
        with:
          otp-version: 22.x
          elixir-version: 1.9.x
      - name: Install Deps
        run: mix deps.get
      - name: Lint
        run: |
          mix format --check-formatted
          mix credo --ignore readability --strict
      - name: Test
        run: mix test --cover
        env:
          MIX_ENV: test
      - name: Build Relase
        if: success()
        run: mix release
        env:
          TC_PUBLIC_API_KEY: ${{ secrets.TC_PUBLIC_API_KEY }}
          TC_PRIVATE_API_KEY: ${{ secrets.TC_PRIVATE_API_KEY }}
          MIX_ENV: prod
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: production
          build_dir: _build/prod
          keep_history: true
          allow_empty_commit: false
          commit_message: "Production deploy"
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

### Logs
[logs_9.zip](https://github.com/crazy-max/ghaction-github-pages/files/5525949/logs_9.zip)
