### ISSUE TITLE
error: src refspec gh-pages does not match any.

### ISSUE THREAD

**Issue by MitchTalmadge** [crazy-max/ghaction-github-pages#17]
Hiya,

I am running into the following error and I haven't been able to determine why:

```
error: src refspec gh-pages does not match any.
error: failed to push some refs to 'https://MitchTalmadge:As provided by GitHub Actions@github.com/MitchTalmadge/CleanTweets.git'
##[error]Docker run failed with exit code 1
```

The odd part to me is the "As provided by GitHub Actions" found in the URL... I know for certain that the PAT secret I am using does contain a personal access token, not anything like that.

The full build logs are found [here.](https://github.com/MitchTalmadge/CleanTweets/commit/d9c0446e72803dd83281b315ff1ee5e29cb9ff99/checks?check_suite_id=294679680)

[Here](https://github.com/MitchTalmadge/CleanTweets/blob/master/.github/workflows/web-frontend.yml) is my workflow:
```
name: Web Frontend

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1.1.0
    - name: Install
      run: npm --prefix web install
    - name: Build
      if: success()
      run: npm --prefix web run build
    - name: Deploy
      if: success()
      uses: crazy-max/ghaction-github-pages@v0.1.0
      env:
        GITHUB_PAT: ${{ secrets.GH_PAT }}
      with:
        build_dir: web/dist
```

The branch does exist in my repo:
![image](https://user-images.githubusercontent.com/8848080/68124500-ca295280-fecc-11e9-828d-18929ad3c0ef.png)

Thanks for any suggestions.

**Comment by crazy-max** [comment]
Hi @MitchTalmadge 

Use `v1` instead of `v0.1.0`

**Comment by MitchTalmadge** [comment]
@crazy-max Thanks! That was simple.

It looks like GitHub's action editor is broken and suggests using 0.1.0 no matter which version is selected in the marketplace search:

![image](https://user-images.githubusercontent.com/8848080/68187010-b7615d00-ff62-11e9-8c0b-bc0b782a09b9.png)

I wonder how I can report this.

**Comment by crazy-max** [comment]
@MitchTalmadge Thanks for your report I will take a look at this!

**Comment by crazy-max** [comment]
@MitchTalmadge Can you give me the link of your screenshot please? For me it looks like:

![image](https://user-images.githubusercontent.com/1951866/68205653-1f4b8e00-ffcb-11e9-9b68-97af27c05008.png)

I think I will add a note at the top of the README on the versioning of the action. On your side you can report this problem to GitHub which seems to be a bug by following this link: https://support.github.com/contact

**Comment by MitchTalmadge** [comment]
Sorry for the delay. The link is:
https://github.com/MitchTalmadge/Portfolio/edit/master/.github/workflows/web-deployment.yml

However you probably won't be able to edit this unless you fork my repo. Try it on your own workflow and it'll probably work. When editing in the GitHub website, a marketplace search area appears on the right. Search for your action and you will see the version mismatch. I made a recording to illustrate this:

![recording](https://i.imgur.com/LqejRCv.gif)

**Comment by ChildishGiant** [comment]
I'm having issues with this when using v2.2.0

https://github.com/ChildishGiant/materialize/runs/2103118571

Here's the relevant part of the workflow:
```
  docs:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Generate docs
        run: |
          npm i
          npm run docs
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2.2.0
        with:
          target_branch: gh-pages
          build_dir: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
