### ISSUE TITLE
Able to destroy main/master

### ISSUE THREAD

**Issue by Technetium1** [crazy-max/ghaction-github-pages#176]
### Behaviour
Wipes branch by default.

#### Steps to reproduce this issue

1. Install action
2. Use it as follows
3. Default overwrites main/master :(

#### Expected behaviour

> Tell me what should happen

A new push should be created

#### Actual behaviour
> Tell me what happens instead

A force push destroys the history and the GitHub workflow that ran it!

### Configuration
YML File below.
* Repository URL (if public): N/A
* Build URL (if public): N/A

This needs to have a warning. The action should not destroy the commit history *by default*. Luckily GitHub support was able to recover my last commit.

Example:
```yml
name: Snake

on:
  # run automatically every 6 hours
  schedule:
    - cron: "0 */6 * * *"

# This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:
  
  push:
    branches:
    - master

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            snake/github-contribution-grid-snake.svg?color_snake=purple
            snake/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=purple
      # push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: master
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

### Logs

https://github.com/Technetium1/Technetium1/actions/runs/2593974297

See also https://github.com/Platane/snk/issues/36
