### ISSUE TITLE
error: src refspec pages does not match any

### ISSUE THREAD

**Issue by TheDanniCraft** [crazy-max/ghaction-github-pages#226]
### Support guidelines

- [X] I've read the [support guidelines](https://github.com/crazy-max/ghaction-github-pages/blob/master/.github/SUPPORT.md)

### I've found a bug and checked that ...

- [x] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

### Description

When I try  to deplyo to the branch I get this error:
```
Pushing ./ directory to pages branch on Wiresense/frontend repo
 /usr/bin/git push --force ***github.com/Wiresense/frontend.git pages
 error: src refspec pages does not match any
 error: failed to push some refs to 'https://github.com/Wiresense/frontend.git'
```

### Expected behaviour

The page should be deployed to the pages branch

### Actual behaviour

The action fails  with the error 
```
  error: src refspec pages does not match any
  error: failed to push some refs to 'https://github.com/Wiresense/frontend.git'
  Error: The process '/usr/bin/git' failed with exit code 1
```

### Steps to reproduce

1. Run the workflow
2. See it fail

### Repository URL

https://github.com/Wiresense/frontend/

### Workflow run URL

https://github.com/Wiresense/frontend/actions/runs/9828926622/job/27142003304

### YAML workflow

```yaml
# Sample workflow for building and deploying a Next.js site to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Deploy Next.js site to Pages

on:
  # Runs on realeses
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Detect package manager 🔎
        id: detect-package-manager
        run: |
          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_OUTPUT
            echo "command=install" >> $GITHUB_OUTPUT
            echo "runner=yarn" >> $GITHUB_OUTPUT
            exit 0
          elif [ -f "${{ github.workspace }}/package.json" ]; then
            echo "manager=npm" >> $GITHUB_OUTPUT
            echo "command=ci" >> $GITHUB_OUTPUT
            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "Unable to determine package manager"
            exit 1
          fi
      - name: Setup Node ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: ${{ steps.detect-package-manager.outputs.manager }}
      - name: Setup Pages ⚙️
        uses: actions/configure-pages@v5
        with:
          # Automatically inject basePath in your Next.js configuration file and disable
          # server side image optimization (https://nextjs.org/docs/api-reference/next/image#unoptimized).
          #
          # You may remove this line if you want to manage the configuration yourself.
          static_site_generator: next
      - name: Restore cache ⚡
        uses: actions/cache@v4
        with:
          path: |
            .next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
      - name: Install dependencies 🔧
        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
      - name: Build with Next.js 🏗️
        run: ${{ steps.detect-package-manager.outputs.runner }} next build
      - name: Store build artifacts 📂
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build
          path: out

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Download build artifacts 📂
        uses: actions/download-artifact@v4
        with:
          name: nextjs-build
      - name: Deploy to GitHub Pages 🚀
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: pages
          build_dir: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

### Workflow logs

2024-07-08T02:51:13.4499751Z Current runner version: '2.317.0'
2024-07-08T02:51:13.4521893Z ##[group]Operating System
2024-07-08T02:51:13.4522838Z Ubuntu
2024-07-08T02:51:13.4523194Z 22.04.4
2024-07-08T02:51:13.4523546Z LTS
2024-07-08T02:51:13.4523919Z ##[endgroup]
2024-07-08T02:51:13.4524312Z ##[group]Runner Image
2024-07-08T02:51:13.4524785Z Image: ubuntu-22.04
2024-07-08T02:51:13.4525218Z Version: 20240630.1.0
2024-07-08T02:51:13.4526237Z Included Software: https://github.com/actions/runner-images/blob/ubuntu22/20240630.1/images/ubuntu/Ubuntu2204-Readme.md
2024-07-08T02:51:13.4527699Z Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240630.1
2024-07-08T02:51:13.4528627Z ##[endgroup]
2024-07-08T02:51:13.4529009Z ##[group]Runner Image Provisioner
2024-07-08T02:51:13.4529505Z 2.0.370.1
2024-07-08T02:51:13.4529879Z ##[endgroup]
2024-07-08T02:51:13.4530843Z ##[group]GITHUB_TOKEN Permissions
2024-07-08T02:51:13.4532374Z Contents: read
2024-07-08T02:51:13.4532965Z Metadata: read
2024-07-08T02:51:13.4533519Z Pages: write
2024-07-08T02:51:13.4534077Z ##[endgroup]
2024-07-08T02:51:13.4536942Z Secret source: Actions
2024-07-08T02:51:13.4537657Z Prepare workflow directory
2024-07-08T02:51:13.5165932Z Prepare all required actions
2024-07-08T02:51:13.5323030Z Getting action download info
2024-07-08T02:51:13.6835522Z Download action repository 'actions/checkout@v4' (SHA:692973e3d937129bcbf40652eb9f2f61becf3332)
2024-07-08T02:51:13.9638877Z Download action repository 'actions/download-artifact@v4' (SHA:fa0a91b85d4f404e444e00e005971372dc801d16)
2024-07-08T02:51:14.1790483Z Download action repository 'crazy-max/ghaction-github-pages@v4' (SHA:c05ee637ec73429400a359430db8e5629f3f2564)
2024-07-08T02:51:14.6488274Z Complete job name: deploy
2024-07-08T02:51:14.7496766Z ##[group]Run actions/checkout@v4
2024-07-08T02:51:14.7497236Z with:
2024-07-08T02:51:14.7497530Z   repository: Wiresense/frontend
2024-07-08T02:51:14.7498100Z   token: ***
2024-07-08T02:51:14.7498395Z   ssh-strict: true
2024-07-08T02:51:14.7498694Z   ssh-user: git
2024-07-08T02:51:14.7499010Z   persist-credentials: true
2024-07-08T02:51:14.7499383Z   clean: true
2024-07-08T02:51:14.7499697Z   sparse-checkout-cone-mode: true
2024-07-08T02:51:14.7500099Z   fetch-depth: 1
2024-07-08T02:51:14.7500388Z   fetch-tags: false
2024-07-08T02:51:14.7500702Z   show-progress: true
2024-07-08T02:51:14.7501003Z   lfs: false
2024-07-08T02:51:14.7501271Z   submodules: false
2024-07-08T02:51:14.7501584Z   set-safe-directory: true
2024-07-08T02:51:14.7501927Z ##[endgroup]
2024-07-08T02:51:14.9367485Z Syncing repository: Wiresense/frontend
2024-07-08T02:51:14.9369611Z ##[group]Getting Git version info
2024-07-08T02:51:14.9370334Z Working directory is '/home/runner/work/frontend/frontend'
2024-07-08T02:51:14.9371257Z [command]/usr/bin/git version
2024-07-08T02:51:14.9371639Z git version 2.45.2
2024-07-08T02:51:14.9392824Z ##[endgroup]
2024-07-08T02:51:14.9414476Z Temporarily overriding HOME='/home/runner/work/_temp/2f929d0c-55d7-4b5e-8f9f-9935e9c974eb' before making global git config changes
2024-07-08T02:51:14.9416153Z Adding repository directory to the temporary git global config as a safe directory
2024-07-08T02:51:14.9419529Z [command]/usr/bin/git config --global --add safe.directory /home/runner/work/frontend/frontend
2024-07-08T02:51:14.9452704Z Deleting the contents of '/home/runner/work/frontend/frontend'
2024-07-08T02:51:14.9456031Z ##[group]Initializing the repository
2024-07-08T02:51:14.9459831Z [command]/usr/bin/git init /home/runner/work/frontend/frontend
2024-07-08T02:51:14.9529152Z hint: Using 'master' as the name for the initial branch. This default branch name
2024-07-08T02:51:14.9530755Z hint: is subject to change. To configure the initial branch name to use in all
2024-07-08T02:51:14.9532361Z hint: of your new repositories, which will suppress this warning, call:
2024-07-08T02:51:14.9533381Z hint:
2024-07-08T02:51:14.9534084Z hint: 	git config --global init.defaultBranch <name>
2024-07-08T02:51:14.9534754Z hint:
2024-07-08T02:51:14.9535298Z hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
2024-07-08T02:51:14.9536516Z hint: 'development'. The just-created branch can be renamed via this command:
2024-07-08T02:51:14.9537170Z hint:
2024-07-08T02:51:14.9537450Z hint: 	git branch -m <name>
2024-07-08T02:51:14.9538260Z Initialized empty Git repository in /home/runner/work/frontend/frontend/.git/
2024-07-08T02:51:14.9543795Z [command]/usr/bin/git remote add origin https://github.com/Wiresense/frontend
2024-07-08T02:51:14.9577089Z ##[endgroup]
2024-07-08T02:51:14.9577697Z ##[group]Disabling automatic garbage collection
2024-07-08T02:51:14.9580938Z [command]/usr/bin/git config --local gc.auto 0
2024-07-08T02:51:14.9609863Z ##[endgroup]
2024-07-08T02:51:14.9610418Z ##[group]Setting up auth
2024-07-08T02:51:14.9616687Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2024-07-08T02:51:14.9647947Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
2024-07-08T02:51:14.9963803Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2024-07-08T02:51:14.9992643Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
2024-07-08T02:51:15.0229064Z [command]/usr/bin/git config --local http.https://github.com/.extraheader AUTHORIZATION: basic ***
2024-07-08T02:51:15.0279882Z ##[endgroup]
2024-07-08T02:51:15.0280785Z ##[group]Fetching the repository
2024-07-08T02:51:15.0289870Z [command]/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 origin +e3c7c1836d6d6722188ec8a319745638724e3aa2:refs/remotes/origin/master
2024-07-08T02:51:15.2446296Z From https://github.com/Wiresense/frontend
2024-07-08T02:51:15.2447824Z  * [new ref]         e3c7c1836d6d6722188ec8a319745638724e3aa2 -> origin/master
2024-07-08T02:51:15.2472063Z ##[endgroup]
2024-07-08T02:51:15.2473009Z ##[group]Determining the checkout info
2024-07-08T02:51:15.2474692Z ##[endgroup]
2024-07-08T02:51:15.2480198Z [command]/usr/bin/git sparse-checkout disable
2024-07-08T02:51:15.2530178Z [command]/usr/bin/git config --local --unset-all extensions.worktreeConfig
2024-07-08T02:51:15.2558042Z ##[group]Checking out the ref
2024-07-08T02:51:15.2562736Z [command]/usr/bin/git checkout --progress --force -B master refs/remotes/origin/master
2024-07-08T02:51:15.2636186Z Reset branch 'master'
2024-07-08T02:51:15.2691406Z branch 'master' set up to track 'origin/master'.
2024-07-08T02:51:15.2694115Z ##[endgroup]
2024-07-08T02:51:15.2696052Z [command]/usr/bin/git log -1 --format='%H'
2024-07-08T02:51:15.2706154Z 'e3c7c1836d6d6722188ec8a319745638724e3aa2'
2024-07-08T02:51:15.3010847Z ##[group]Run actions/download-artifact@v4
2024-07-08T02:51:15.3011298Z with:
2024-07-08T02:51:15.3011560Z   name: nextjs-build
2024-07-08T02:51:15.3011891Z   merge-multiple: false
2024-07-08T02:51:15.3012221Z   repository: Wiresense/frontend
2024-07-08T02:51:15.3012578Z   run-id: 9828926622
2024-07-08T02:51:15.3012851Z ##[endgroup]
2024-07-08T02:51:15.5031465Z Downloading single artifact
2024-07-08T02:51:15.5901446Z Preparing to download the following artifacts:
2024-07-08T02:51:15.5902405Z - nextjs-build (ID: 1675315583, Size: 755839)
2024-07-08T02:51:15.6356493Z Redirecting to blob download url: https://productionresultssa9.blob.core.windows.net/actions-results/c0fcc937-1504-4a13-b52c-bc03257c95e3/workflow-job-run-ca395085-040a-526b-2ce8-bdc85f692774/artifacts/2a6a4be4072a8d68ee38e6a93aa0f3f3ea92b352db4bcc86016839025edd523e.zip
2024-07-08T02:51:15.6359927Z Starting download of artifact to: /home/runner/work/frontend/frontend
2024-07-08T02:51:15.7079542Z (node:1729) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
2024-07-08T02:51:15.7081735Z (Use `node --trace-deprecation ...` to show where the warning was created)
2024-07-08T02:51:15.7574945Z Artifact download completed successfully.
2024-07-08T02:51:15.7575730Z Total of 1 artifact(s) downloaded
2024-07-08T02:51:15.7580943Z Download artifact has finished successfully
2024-07-08T02:51:15.7739388Z ##[group]Run crazy-max/ghaction-github-pages@v4
2024-07-08T02:51:15.7740110Z with:
2024-07-08T02:51:15.7740446Z   target_branch: pages
2024-07-08T02:51:15.7740866Z   build_dir: ./
2024-07-08T02:51:15.7741313Z   domain: github.com
2024-07-08T02:51:15.7741676Z   keep_history: false
2024-07-08T02:51:15.7742092Z   allow_empty_commit: true
2024-07-08T02:51:15.7742594Z   absolute_build_dir: false
2024-07-08T02:51:15.7743008Z   follow_symlinks: false
2024-07-08T02:51:15.7743472Z   jekyll: true
2024-07-08T02:51:15.7743895Z   dry_run: false
2024-07-08T02:51:15.7744227Z   verbose: false
2024-07-08T02:51:15.7744614Z env:
2024-07-08T02:51:15.7745273Z   GITHUB_TOKEN: ***
2024-07-08T02:51:15.7745628Z ##[endgroup]
2024-07-08T02:51:16.0209874Z ##[group]Initializing local git repo
2024-07-08T02:51:16.0225304Z [command]/usr/bin/git init .
2024-07-08T02:51:16.0266785Z hint: Using 'master' as the name for the initial branch. This default branch name
2024-07-08T02:51:16.0268572Z hint: is subject to change. To configure the initial branch name to use in all
2024-07-08T02:51:16.0269938Z hint: of your new repositories, which will suppress this warning, call:
2024-07-08T02:51:16.0273586Z hint:
2024-07-08T02:51:16.0274457Z hint: 	git config --global init.defaultBranch <name>
2024-07-08T02:51:16.0275385Z hint:
2024-07-08T02:51:16.0276560Z hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
2024-07-08T02:51:16.0278032Z hint: 'development'. The just-created branch can be renamed via this command:
2024-07-08T02:51:16.0279004Z hint:
2024-07-08T02:51:16.0279751Z hint: 	git branch -m <name>
2024-07-08T02:51:16.0280720Z Initialized empty Git repository in /tmp/github-pages-w60kQR/.git/
2024-07-08T02:51:16.0343356Z [command]/usr/bin/git checkout --orphan pages
2024-07-08T02:51:16.0344698Z Switched to a new branch 'pages'
2024-07-08T02:51:16.0345868Z ##[endgroup]
2024-07-08T02:51:16.0347561Z ##[group]Copying /home/runner/work/frontend/frontend/ to /tmp/github-pages-w60kQR
2024-07-08T02:51:16.0646597Z ................................................................................
2024-07-08T02:51:16.0863066Z ................................................................................
2024-07-08T02:51:16.0923504Z ..................178 file(s) copied.
2024-07-08T02:51:16.0924679Z ##[endgroup]
2024-07-08T02:51:16.0990912Z ##[group]Configuring git committer
2024-07-08T02:51:16.1001013Z [command]/usr/bin/git config user.name GitHub
2024-07-08T02:51:16.1038951Z [command]/usr/bin/git config user.email noreply@github.com
2024-07-08T02:51:16.1064955Z ##[endgroup]
2024-07-08T02:51:16.1117267Z ##[group]Updating index of working tree
2024-07-08T02:51:16.1128301Z [command]/usr/bin/git add --all .
2024-07-08T02:51:16.1586179Z ##[endgroup]
2024-07-08T02:51:16.1587844Z ##[group]Committing changes
2024-07-08T02:51:16.1603962Z [command]/usr/bin/git commit --allow-empty --author github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com> --message Deploy to GitHub pages
2024-07-08T02:51:16.1773639Z [master 5012f9c] Deploy to GitHub pages
2024-07-08T02:51:16.1775404Z  Author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
2024-07-08T02:51:16.1776415Z  31 files changed, 130 insertions(+)
2024-07-08T02:51:16.1777079Z  create mode 100644 404.html
2024-07-08T02:51:16.1777913Z  create mode 100644 _next/static/bmNDXovabqt0RZlOdqEGf/_buildManifest.js
2024-07-08T02:51:16.1779176Z  create mode 100644 _next/static/bmNDXovabqt0RZlOdqEGf/_ssgManifest.js
2024-07-08T02:51:16.1780596Z  create mode 100644 _next/static/chunks/23-d98e7b1e40dff78b.js
2024-07-08T02:51:16.1782030Z  create mode 100644 _next/static/chunks/330-7f8f2da3293f1dff.js
2024-07-08T02:51:16.1783262Z  create mode 100644 _next/static/chunks/662-443588f7a66c2755.js
2024-07-08T02:51:16.1784949Z  create mode 100644 _next/static/chunks/957-ff9215fab31f5815.js
2024-07-08T02:51:16.1786696Z  create mode 100644 _next/static/chunks/app/_not-found/page-d7c4207c2f0da251.js
2024-07-08T02:51:16.1788576Z  create mode 100644 _next/static/chunks/app/layout-fc5395819773e33a.js
2024-07-08T02:51:16.1790099Z  create mode 100644 _next/static/chunks/app/page-0d494e35ac85b209.js
2024-07-08T02:51:16.1791672Z  create mode 100644 _next/static/chunks/c16f53c3-98068730cd2136da.js
2024-07-08T02:51:16.1793107Z  create mode 100644 _next/static/chunks/fd9d1056-c5e065504e7d5b56.js
2024-07-08T02:51:16.1794435Z  create mode 100644 _next/static/chunks/framework-00a8ba1a63cfdc9e.js
2024-07-08T02:51:16.1795908Z  create mode 100644 _next/static/chunks/main-3e5d46ba9140c556.js
2024-07-08T02:51:16.1797175Z  create mode 100644 _next/static/chunks/main-app-e7ac145d70c817a6.js
2024-07-08T02:51:16.1798416Z  create mode 100644 _next/static/chunks/pages/_app-037b5d058bd9a820.js
2024-07-08T02:51:16.1799928Z  create mode 100644 _next/static/chunks/pages/_error-6ae619510b1539d6.js
2024-07-08T02:51:16.1801352Z  create mode 100644 _next/static/chunks/polyfills-78c92fac7aa8fdd8.js
2024-07-08T02:51:16.1802778Z  create mode 100644 _next/static/chunks/webpack-451c4b961bcb1ebf.js
2024-07-08T02:51:16.1803947Z  create mode 100644 _next/static/css/6a41146d66ebb5e0.css
2024-07-08T02:51:16.1804527Z  create mode 100644 _next/static/css/f878c3463ec02756.css
2024-07-08T02:51:16.1805309Z  create mode 100644 _next/static/media/05a31a2ca4975f99-s.woff2
2024-07-08T02:51:16.1806100Z  create mode 100644 _next/static/media/513657b02c5c193f-s.woff2
2024-07-08T02:51:16.1806766Z  create mode 100644 _next/static/media/51ed15f9841b9f9d-s.woff2
2024-07-08T02:51:16.1807496Z  create mode 100644 _next/static/media/c9a5bc6a7c948fb0-s.p.woff2
2024-07-08T02:51:16.1808116Z  create mode 100644 _next/static/media/d6b16ce4a6175f26-s.woff2
2024-07-08T02:51:16.1808760Z  create mode 100644 _next/static/media/ec159349637c90ad-s.woff2
2024-07-08T02:51:16.1809887Z  create mode 100644 _next/static/media/fd4db3eb5472fc27-s.woff2
2024-07-08T02:51:16.1810775Z  create mode 100644 favicon.ico
2024-07-08T02:51:16.1811470Z  create mode 100644 index.html
2024-07-08T02:51:16.1812247Z  create mode 100644 index.txt
2024-07-08T02:51:16.1940361Z commit 5012f9c15ce53224b74ae2ee7eca1db20daff2a2
2024-07-08T02:51:16.1941834Z Author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
2024-07-08T02:51:16.1942863Z Date:   Mon Jul 8 02:51:16 2024 +0000
2024-07-08T02:51:16.1943407Z 
2024-07-08T02:51:16.1943936Z     Deploy to GitHub pages
2024-07-08T02:51:16.1944494Z 
2024-07-08T02:51:16.1945028Z  404.html                                           |   7 +++
2024-07-08T02:51:16.1946250Z  .../static/bmNDXovabqt0RZlOdqEGf/_buildManifest.js |   1 +
2024-07-08T02:51:16.1947314Z  _next/static/bmNDXovabqt0RZlOdqEGf/_ssgManifest.js |   1 +
2024-07-08T02:51:16.1948404Z  _next/static/chunks/23-d98e7b1e40dff78b.js         |   2 +
2024-07-08T02:51:16.1949169Z  _next/static/chunks/330-7f8f2da3293f1dff.js        |   1 +
2024-07-08T02:51:16.1950176Z  _next/static/chunks/662-443588f7a66c2755.js        |   1 +
2024-07-08T02:51:16.1951169Z  _next/static/chunks/957-ff9215fab31f5815.js        |  53 +++++++++++++++++++++
2024-07-08T02:51:16.1951897Z  .../chunks/app/_not-found/page-d7c4207c2f0da251.js |   1 +
2024-07-08T02:51:16.1952916Z  _next/static/chunks/app/layout-fc5395819773e33a.js |   1 +
2024-07-08T02:51:16.1953936Z  _next/static/chunks/app/page-0d494e35ac85b209.js   |   1 +
2024-07-08T02:51:16.1954566Z  _next/static/chunks/c16f53c3-98068730cd2136da.js   |   1 +
2024-07-08T02:51:16.1955157Z  _next/static/chunks/fd9d1056-c5e065504e7d5b56.js   |   1 +
2024-07-08T02:51:16.1955916Z  _next/static/chunks/framework-00a8ba1a63cfdc9e.js  |  33 +++++++++++++
2024-07-08T02:51:16.1957081Z  _next/static/chunks/main-3e5d46ba9140c556.js       |   1 +
2024-07-08T02:51:16.1958107Z  _next/static/chunks/main-app-e7ac145d70c817a6.js   |   1 +
2024-07-08T02:51:16.1959272Z  _next/static/chunks/pages/_app-037b5d058bd9a820.js |   1 +
2024-07-08T02:51:16.1960624Z  .../static/chunks/pages/_error-6ae619510b1539d6.js |   1 +
2024-07-08T02:51:16.1961692Z  _next/static/chunks/polyfills-78c92fac7aa8fdd8.js  |   1 +
2024-07-08T02:51:16.1963406Z  _next/static/chunks/webpack-451c4b961bcb1ebf.js    |   1 +
2024-07-08T02:51:16.1964201Z  _next/static/css/6a41146d66ebb5e0.css              |   3 ++
2024-07-08T02:51:16.1964781Z  _next/static/css/f878c3463ec02756.css              |   1 +
2024-07-08T02:51:16.1965582Z  _next/static/media/05a31a2ca4975f99-s.woff2        | Bin 0 -> 10496 bytes
2024-07-08T02:51:16.1966371Z  _next/static/media/513657b02c5c193f-s.woff2        | Bin 0 -> 17612 bytes
2024-07-08T02:51:16.1967130Z  _next/static/media/51ed15f9841b9f9d-s.woff2        | Bin 0 -> 22524 bytes
2024-07-08T02:51:16.1967952Z  _next/static/media/c9a5bc6a7c948fb0-s.p.woff2      | Bin 0 -> 46552 bytes
2024-07-08T02:51:16.1968711Z  _next/static/media/d6b16ce4a6175f26-s.woff2        | Bin 0 -> 80044 bytes
2024-07-08T02:51:16.1969469Z  _next/static/media/ec159349637c90ad-s.woff2        | Bin 0 -> 27316 bytes
2024-07-08T02:51:16.1970432Z  _next/static/media/fd4db3eb5472fc27-s.woff2        | Bin 0 -> 12768 bytes
2024-07-08T02:51:16.1971113Z  favicon.ico                                        | Bin 0 -> 43754 bytes
2024-07-08T02:51:16.1971672Z  index.html                                         |   7 +++
2024-07-08T02:51:16.1972288Z  index.txt                                          |   9 ++++
2024-07-08T02:51:16.1972773Z  31 files changed, 130 insertions(+)
2024-07-08T02:51:16.1973702Z ##[endgroup]
2024-07-08T02:51:16.1974456Z ##[group]Pushing ./ directory to pages branch on Wiresense/frontend repo
2024-07-08T02:51:16.1976276Z [command]/usr/bin/git push --force ***github.com/Wiresense/frontend.git pages
2024-07-08T02:51:16.2036423Z error: src refspec pages does not match any
2024-07-08T02:51:16.2037811Z error: failed to push some refs to 'https://github.com/Wiresense/frontend.git'
2024-07-08T02:51:16.2082108Z ##[error]The process '/usr/bin/git' failed with exit code 1
2024-07-08T02:51:16.2191519Z Post job cleanup.
2024-07-08T02:51:16.3101979Z [command]/usr/bin/git version
2024-07-08T02:51:16.3140418Z git version 2.45.2
2024-07-08T02:51:16.3188247Z Temporarily overriding HOME='/home/runner/work/_temp/84148564-b370-44b9-b757-11bdc8ad19b9' before making global git config changes
2024-07-08T02:51:16.3189371Z Adding repository directory to the temporary git global config as a safe directory
2024-07-08T02:51:16.3195212Z [command]/usr/bin/git config --global --add safe.directory /home/runner/work/frontend/frontend
2024-07-08T02:51:16.3232416Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2024-07-08T02:51:16.3264835Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :"
2024-07-08T02:51:16.3504400Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2024-07-08T02:51:16.3526788Z http.https://github.com/.extraheader
2024-07-08T02:51:16.3539806Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2024-07-08T02:51:16.3574762Z [command]/usr/bin/git submodule foreach --recursive sh -c "git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :"
2024-07-08T02:51:16.4005011Z Evaluate and set environment url
2024-07-08T02:51:16.4008961Z Evaluated environment url: 
2024-07-08T02:51:16.4009619Z Cleaning up orphan processes
